name: 'testing'
description: 'test download zip files'
inputs:
  token:  # id of input
    description: 'token'
    required: false
  owner:  # id of input
    description: 'owner'
    required: true    
  repo:  # id of input
    description: 'repo'
    required: true    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}